---
title: "Testing LightBox For Figures"
format: html
lightbox: auto
---


## With computation code chunks

Options for lightbox can be passed using chunk options.

```{r}
#| fig-cap: Simple demo R plot 
#| lightbox:
#|   group: r-graph
#|   description: This is 1 to 10 plot
plot(1:10, rnorm(10))
```

```{r}
#| fig-cap: Plot about cars data
#| lightbox:
#|   group: r-graph
#|   description: We see our cars data above
plot(cars)
```

It is possible to create several plots, and group them in a lightbox gallery. Use list in YAML for options when you have several plots, on per plot.
```{r}
#| fig-cap: 
#|   - Caption for first plot
#|   - Caption for second plot
#| lightbox: 
#|   group: cars
#|   description: 
#|     - This is the decription for first graph
#|     - This is the decription for second graph
plot(mtcars)
plot(cars)
```

When `lightbox: auto` in main YAML config, you can opt-out lightbox on a plot by setting `lightbox: false`

```{r}
#| fig-cap: mtcars
#| lightbox: false
plot(mtcars)
```
